### ISSUE TITLE
About RNN part

### ISSUE THREAD

**Issue by nmhkahn** [JamesChuanggg/vqa-tf#3]
Hi, thanks your repo.

and I have some questions, like in your rnn part code, you init `embed_state_W` as `2*rnn_size*rnn_layer`.
But what if I only take last output of RNN part (so dim must be rnn_layer) then performance get worse?

Actually I also convert VQA_LSTM_CNN code to tensorflow and my codes are really similar to yours except RNN part. (I only get last output of dynamic_RNN API)
But I only achieve around 54 with train/val training and test evaluation (and also use ResNet feature instead of VGG :( ).

Thanks.

**Comment by chingyaoc** [comment]
Hi,
RNN part I simply follow the original [code](https://github.com/VT-vision-lab/VQA_LSTM_CNN/blob/master/train.lua#L139).
Maybe you should use "hidden state" instead of the "output" since hidden state usually contains more information rather than the output. The other VQA papers also use hidden state as textual representation. Hope it helps :) .

**Comment by nmhkahn** [comment]
Thanks for your reply 👍
